### ISSUE TITLE
Strange behaviour of ctg books

### ISSUE THREAD

**Issue by MisesEnForce** [peterosterlund2/droidfish#60]
So far I used CTG books provided by ChessBase without any problem, never spotted anything strange regarding lines probabilities etc. Today, from the Mega DataBase 2020 I created the database of all 1.e4 c5 games, from which with Fritz I created a CTG book. (There's two ways, absolute or ECO-related, to create a book, I tried both and what follows remains true for both.) Then I used the book in DroidFish and played until 1.e4 c5 2.Nf3 d6 3.d4 cxd4 4.Nxd4 Nf6 5.Nc3 to see this : 

![image](https://user-images.githubusercontent.com/5349602/94371254-6e277800-00f5-11eb-91cb-e133618adc3c.png)

The Dragon 5...g6 is played 64% of the time while the Najdorf 5...a6 is only played 22% of time, which is false by experience, and be a simple look at the Mega DataBase 2020 ! I don't know if the problem comes from how with ChessBase+Fritz I created the CTG book, or if it does come from DroidFish because the CTG created this way is maybe not properly handled by DroidFIsh.

The book is [here](https://www.dropbox.com/sh/b10neo0ti50imga/AAAqB6fL-1pkcfZS28cg7NAQa?dl=0) (in two versions, corresponding to the ChessBase+Fritz ways of creating it) for debugging purposes if needed.

**Comment by peterosterlund2** [comment]
The problem is that the CTG book format is undocumented (as far as I know), so DroidFish makes no attempt to calculate the same move probabilities as ChessBase would calculate. DroidFish uses a quite simple weight calculation based only on the move annotations stored in the opening book.

**Comment by MisesEnForce** [comment]
Well the CTG book format is somehow documented [here](http://rybkaforum.net/cgi-bin/rybkaforum/topic_show.pl?tid=2319). As DroidFIsh use weight calculations based on move annotations in the book, I guess that there are two cases : 

1. Vanilla CTG book, for instance bought from ChessBase :: never had such a problem with it, all probabilities match expected probabilities, at least for lines I know well, must be the same for other lines
2. CTG book created from a ChessBase database following ChessBase recommandations : problem.

I guess that in the first case the quantities you parse out from annotations are at some place whereas in the second case, they aren't and are at another, explainig why wrong probabilities are calculated. (See 1.4.9. Position statistics from the aforementionned link.)

**Comment by peterosterlund2** [comment]
I added some logging to DroidFish and for the position in question the following data is retrieved/calculated for each move:

    move    w0   score     weight
    e2e3 1.000   38499   38499.00
    a2a3 1.000  201998  201998.00
    g2g3 8.000   74947  599576.00
    b1d2 0.500     416     208.00
    b1c3 1.000   92035   92035.00
    e2e4 0.125    1570     196.25
    c1d2 0.125    1970     246.25
    h2h3 1.000      69      69.00
    g2g4 1.000       1       1.00
    d1c2 1.000      14      14.00
    c1g5 1.000       8       8.00
    b2b3 0.000      15       0.00
    d1a4 1.000       8       8.00
    c1e3 1.000       2       2.00
    b1a3 1.000       7       7.00
    d1b3 1.000      10      10.00
    d3d4 1.000       0       0.00
    f3g1 1.000       4       4.00
Note that CTG books always store positions where white is to move, so this position was mirrored before being stored in the book.
The `w0` value [is calculated](https://github.com/peterosterlund2/droidfish/blob/ce2e5a326abe8797067c974fe46a852c14c3494b/DroidFishApp/src/main/java/org/petero/droidfish/book/CtgBook.java#L406) from the move annotation and the `score` value [is calculated](https://github.com/peterosterlund2/droidfish/blob/ce2e5a326abe8797067c974fe46a852c14c3494b/DroidFishApp/src/main/java/org/petero/droidfish/book/CtgBook.java#L421) from the WDL statistics for the move. The `weight` is simply `w0 * score` and is what gives the play percentage values after normalization.
In this case the `g6` move gets an 8x boost because it is annotated as `!`. Possibly ChessBase does not actually use annotations to determine move probabilities, but I don't have ChessBase so I cannot verify this.

**Comment by MisesEnForce** [comment]
Here's what Fritz shows for the position and the opening book :
![image](https://user-images.githubusercontent.com/5349602/94374564-7c818e00-010d-11eb-8aae-9a79d69eea3e.png)
What I don't understand in you previous message is the following : I get that *8 multiplication because 5...g6 (a2a3 has we have mirroring) has a "!" annotation, but what I don't get is that the move cannot for sure have this annotation in all games, so that the score should be multiplied by 8. (I may not understand correctly the CTG structure.)

I don't think ChessBase uses annotations at all, as pointed in the [CTG "documentation"](http://rybkaforum.net/cgi-bin/rybkaforum/topic_show.pl?tid=2319) : 

1.4.9. Position statistics

After all moves and annotations have been encoded, the statistics for this
position are stored:

  - First, a three-byte integer describing the number of games for this
    position. This is the number reported in parenthesises after "N = 12345"
    in Chessbase. (The "real" N number is the sum of the number of wins,
    draws and losses.)
  - Then, three bytes describing the number of wins for white (1-0). Remember
    that the position is always stored from white's perspective, so if black
    is to move, one will need to swap the numbers for 1-0 and 0-1.
  - Then, three bytes describing the number of wins for black (0-1).
  - Then, three bytes describing the number of draws (1/2).

Intuitively, I would say this : we shouldn't use the annotation in the calculation because the annotation is already contained "somehowe" in the fact that the move is very often played and with "ok" statistics.

**Comment by peterosterlund2** [comment]
I think the annotations do affect the play probability `[%]`. This is the only reason I can think of to explain that `[%]` is larger than `Prob` for the `g6` move (22.6% vs 18.7%). The effect seems to be a lot smaller than the 8x factor I use in DroidFish though.

I used to believe that these annotations were something that was modified manually for certain positions/moves and not something that was computed from the input games, since as you say there is no reason to believe that all games will have the same annotation for the same position/move. That was only a guess though and it is possible that the annotations can also be set automatically somehow based on the input PGN data.

It seems to me that average Elo is also included in the `Prob` calculation somehow. If the `g6` move is compared to the `Nc6` and `e6` moves, it can be seen that `Prob(g6)` is roughly halfway between `Prob(e6)` and `Prob(Nc6)` even though `N(g6)` is much closer to `N(Nc6)` than `N(e6)` and `g6` has a better percentage `%` than both `e6` and `Nc6`. This is perhaps because `Av(g6)` is lower than both `Av(e6)` and `Av(Nc6)`.

**Comment by MisesEnForce** [comment]
See for instance this [answer ](https://chess.stackexchange.com/a/15363/20949) about the quantities N, %, Av, Perf, Fact, Prob and [%] in the "reference" panel of ChessBase, which uses the same "module" that the one I screenshot for the opening book.

It appears that they all quantities are completely broken ... _Hence I think one should better focus for each M at a position P to the ratio "number of games where M was played after P divided by number of games with position P"_. By focus I mean "display" in the lower part of the screen in DroidFish (line on which I put a red circle in the question). Because this quantity is somehow absolute and does not rely in methods, suppositions etc, that could be wrong (and that are in ChessBase). At least while we don't know the forlumas used.

I will try to look in ChessBase/Fritz manuals to see if they give formulas used for this.

**Comment by MisesEnForce** [comment]
![Screenshot_20200928-001120_Acrobat for Samsung](https://user-images.githubusercontent.com/5349602/94377130-5f55bb00-011f-11eb-8a75-7e769806d247.jpg)
![Screenshot_20200928-001132_Acrobat for Samsung](https://user-images.githubusercontent.com/5349602/94377135-67155f80-011f-11eb-8bd6-feeb5237a55a.jpg)

**Comment by peterosterlund2** [comment]
I adjusted the factor for `!` from 8 to 1.23, the factor for `?!` from 0.125 to 0, and the factor for `!?` from 0.5 to 1, based on your example. I still have no examples for `!!` and `only move` so I don't know what those factors should be. A test version with those modifications is available [here](https://www.dropbox.com/s/mjj406i4vdxj9jg/DroidFish.apk?dl=1).

It seems from the manual that it is possible to right click on a move and change the annotation in Fritz. If you could do that for the `g6` move and try the `!!` and `only move` annotations, I could adjust those factors too.

**Comment by peterosterlund2** [comment]
> _Hence I think one should better focus for each M at a position P to the ratio "number of games where M was played after P divided by number of games with position P"_.

That information is not stored in the book though. Instead the best you can get is "number of games containing the position that results from playing M in position P". This is not the same due to possible transpositions.

Consider this move sequence. "e4 e5 Nf3 a6 Bb5". The statistics would likely indicate that Nc6 should be played because it leads to a very common position, although axb5 would be much better. I think the move annotations are needed to fix such problems, although in practice the positions will not be as extreme as in my made up example.

**Comment by MisesEnForce** [comment]
For "5...g6!!" only the last column "[%]" changed from 22.6 to 25.8 : 
![image](https://user-images.githubusercontent.com/5349602/94396510-5afec180-0162-11eb-9153-a6aa6baaa86e.png)
You can find the associated CTG files [here](https://www.dropbox.com/sh/9ttm7y700u2is71/AABBAhe--KIsFdY94zZN4iPKa?dl=0)  (only the ctg changes, not the CTB nor the CTO).

For "5...g6 only move" also only the last column "[%]" changed from 22.6 to 19.2 : 
![image](https://user-images.githubusercontent.com/5349602/94396772-f09a5100-0162-11eb-971d-04e3e72c9004.png)
You can find the associated CTG files [here](https://www.dropbox.com/sh/98b16hvpz9e3o8u/AACwz-KDFATNYT6Ehq1qsX3ma?dl=0) (again only the ctg changes, not the CTB nor the CTO).

The complete list of moves qualifiers is : 
![image](https://user-images.githubusercontent.com/5349602/94397283-cd23d600-0163-11eb-80d6-6939120a780d.png)

You also have the complete list of position qualifiers : 
![image](https://user-images.githubusercontent.com/5349602/94397341-ed539500-0163-11eb-833e-5a034d62b173.png)
but I don't think they change the "[%]" variables or other variables. We could do the test if you need.

**Comment by MisesEnForce** [comment]
> > _Hence I think one should better focus for each M at a position P to the ratio "number of games where M was played after P divided by number of games with position P"_.
> 
> That information is not stored in the book though. Instead the best you can get is "number of games containing the position that results from playing M in position P". This is not the same due to possible transpositions.
> 
> Consider this move sequence. "e4 e5 Nf3 a6 Bb5". The statistics would likely indicate that Nc6 should be played because it leads to a very common position, although axb5 would be much better. I think the move annotations are needed to fix such problems, although in practice the positions will not be as extreme as in my made up example.

Got you, ok. Would have made more sense to also store the absolute number of games pre/ex moves, damn ChessBase ... :)

**Comment by peterosterlund2** [comment]
Thanks for the information. I have adjusted the weight calculation based on your examples and uploaded a new version [here](https://www.dropbox.com/s/mjj406i4vdxj9jg/DroidFish.apk?dl=1). Hopefully there are now no big differences compared to ChessBase/Fritz.

My calculation still does not take performance Elo into account, but I guess that is not very important.

**Comment by MisesEnForce** [comment]
> Thanks for the information. I have adjusted the weight calculation based on your examples and uploaded a new version [here](https://www.dropbox.com/s/mjj406i4vdxj9jg/DroidFish.apk?dl=1). Hopefully there are now no big differences compared to ChessBase/Fritz.
> 
> My calculation still does not take performance Elo into account, but I guess that is not very important.

I confirm after having rapidly tested during commuting that it is quite in line with what I observe in ChessBase. You can indeed push these modifications !

Thank you very much, really. For your excellent app of course, for maintaining it thoroughly, and for your reactivity !
